############################################################################
# Barn swallow pairwise LD between trait-associated regions (sig. SNPs)
############################################################################

# We've calculated linkage disequilibrium (r2) between significant SNPs in 
# candidate genomic regions assocaited with traits.

# Here, we'll examine summaries of r2 between each pair of regions.

# This script contains commands for reading in r2 values for sets of SNPs in
# candidate regions, summarizing r2 distributions, and plotting.

### Clear environment-------------------------------------------------------

rm(list = ls())

### Working directory and dependencies--------------------------------------

setwd('./analysis/ld')

library(data.table)
library(tidyverse)
library(ggplot2)
library(scales)

### Read in data------------------------------------------------------------

rt.means <- read.table('./r2_pairwise/r2.candidate.afd.all.rustica-tytleri.table-mean_no-self.txt',header=T)
rg.means <- read.table('./r2_pairwise/r2.candidate.afd.all.rustica-gutturalis.table-mean_no-self.txt',header=T)
tg.means <- read.table('./r2_pairwise/r2.candidate.afd.all.tytleri-gutturalis.table-mean_no-self.txt',header=T)

### Transform to long format------------------------------------------------

rtm2 <- rt.means %>%
  rownames_to_column() %>%
  gather(colname, value, -rowname)

rgm2 <- rg.means %>%
  rownames_to_column() %>%
  gather(colname, value, -rowname)

tgm2 <- tg.means %>%
  rownames_to_column() %>%
  gather(colname, value, -rowname)

### Plot pairwise heatplots-------------------------------------------------

ggplot(rtm2, aes(x = colname, y = rowname, fill = value)) +
  geom_tile()+
  geom_tile(color = "black") +
  scale_fill_gradient(low = "white", high = "red") +
  geom_text(aes(label = value), color = "black", size = 4) +
  scale_y_discrete(limits=rev)

ggplot(rgm2, aes(x = colname, y = rowname, fill = value)) +
  geom_tile()+
  geom_tile(color = "black") +
  scale_fill_gradient(low = "white", high = "red") +
  geom_text(aes(label = value), color = "black", size = 4) +
  scale_y_discrete(limits=rev)

ggplot(tgm2, aes(x = colname, y = rowname, fill = value)) +
  geom_tile()+
  geom_tile(color = "black") +
  scale_fill_gradient(low = "white", high = "red") +
  geom_text(aes(label = value), color = "black", size = 4) +
  scale_y_discrete(limits=rev)

### Read in raw data-------------------------------------------------------

## LD inputs (if means have not already been calculated)
r2.sig.intra.rt <- read.table('./r2_pairwise/r2.candidate.afd.rustica-tytleri.hap.ld',header=T)
r2.sig.inter.rt <- read.table('./r2_pairwise/r2.candidate.afd.rustica-tytleri.interchrom.hap.ld',header=T)
r2.sig.intra.rg <- read.table('./r2_pairwise/r2.candidate.afd.rustica-gutturalis.hap.ld',header=T)
r2.sig.inter.rg <- read.table('./r2_pairwise/r2.candidate.afd.rustica-gutturalis.interchrom.hap.ld',header=T)
r2.sig.intra.tg <- read.table('./r2_pairwise/r2.candidate.afd.tytleri-gutturalis.hap.ld',header=T)
r2.sig.inter.tg <- read.table('./r2_pairwise/r2.candidate.afd.tytleri-gutturalis.interchrom.hap.ld',header=T)

r2.sig.intra.rt <- r2.sig.intra.rt[which(r2.sig.intra.rt$Dprime>=0),]
r2.sig.intra.rg <- r2.sig.intra.rg[which(r2.sig.intra.rg$Dprime>=0),]
r2.sig.intra.tg <- r2.sig.intra.tg[which(r2.sig.intra.tg$Dprime>=0),]

cand <- read.table('candidate_regions.txt',header=T)

### Define pairwise sets of SNPs--------------------------------------------

## Only need to do this if the tables of pairwise means have not been read in

r2.kitlg.kitlg.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & POS2 >= cand$start[1] & POS2 <= cand$end[1])
r2.kitlg.plxnc1.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & POS2 >= cand$start[2] & POS2 <= cand$end[2])
r2.kitlg.spef2.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[3] & POS2 >= cand$start[3] & POS2 <= cand$end[3])
r2.kitlg.slc45a2.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[4] & POS2 >= cand$start[4] & POS2 <= cand$end[4])
r2.kitlg.bnc2.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[5] & POS2 >= cand$start[5] & POS2 <= cand$end[5])
r2.kitlg.gnaq.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[6] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.kitlg.ror2.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[7] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.kitlg.apc.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[8] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.kitlg.ice1.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[9] & POS2 >= cand$start[9] & POS2 <= cand$end[9])
r2.kitlg.pde1c.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[10] & POS2 >= cand$start[10] & POS2 <= cand$end[10])
r2.plxnc1.plxnc1.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & POS2 >= cand$start[2] & POS2 <= cand$end[2])
r2.plxnc1.spef2.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[3] & POS2 >= cand$start[3] & POS2 <= cand$end[3])
r2.plxnc1.slc45a2.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[4] & POS2 >= cand$start[4] & POS2 <= cand$end[4])
r2.plxnc1.bnc2.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[5] & POS2 >= cand$start[5] & POS2 <= cand$end[5])
r2.plxnc1.gnaq.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[6] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.plxnc1.ror2.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[7] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.plxnc1.apc.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[8] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.plxnc1.ice1.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[9] & POS2 >= cand$start[9] & POS2 <= cand$end[9])
r2.plxnc1.pde1c.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[10] & POS2 >= cand$start[10] & POS2 <= cand$end[10])
r2.spef2.spef2.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[3] & POS1 >= cand$start[3] & POS1 <= cand$end[3] & POS2 >= cand$start[3] & POS2 <= cand$end[3])
r2.spef2.slc45a2.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[3] & POS1 >= cand$start[3] & POS1 <= cand$end[3] & POS2 >= cand$start[4] & POS2 <= cand$end[4])
r2.spef2.bnc2.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[3] & POS1 >= cand$start[3] & POS1 <= cand$end[3] & POS2 >= cand$start[5] & POS2 <= cand$end[5])
r2.spef2.gnaq.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[3] & POS1 >= cand$start[3] & POS1 <= cand$end[3] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.spef2.ror2.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[3] & POS1 >= cand$start[3] & POS1 <= cand$end[3] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.spef2.apc.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[3] & POS1 >= cand$start[3] & POS1 <= cand$end[3] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.spef2.ice1.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & CHR2 == cand$chrom[3] & POS2 >= cand$start[3] & POS2 <= cand$end[3])
r2.spef2.pde1c.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[10] & POS1 >= cand$start[10] & POS1 <= cand$end[10] & CHR2 == cand$chrom[3] & POS2 >= cand$start[3] & POS2 <= cand$end[3])
r2.slc45a2.slc45a2.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[4] & POS1 >= cand$start[4] & POS1 <= cand$end[4] & POS2 >= cand$start[4] & POS2 <= cand$end[4])
r2.slc45a2.bnc2.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[4] & POS1 >= cand$start[4] & POS1 <= cand$end[4] & POS2 >= cand$start[5] & POS2 <= cand$end[5])
r2.slc45a2.gnaq.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[4] & POS1 >= cand$start[4] & POS1 <= cand$end[4] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.slc45a2.ror2.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[4] & POS1 >= cand$start[4] & POS1 <= cand$end[4] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.slc45a2.apc.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[4] & POS1 >= cand$start[4] & POS1 <= cand$end[4] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.slc45a2.ice1.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & CHR2 == cand$chrom[4] & POS2 >= cand$start[4] & POS2 <= cand$end[4])
r2.slc45a2.pde1c.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[10] & POS1 >= cand$start[10] & POS1 <= cand$end[10] & CHR2 == cand$chrom[4] & POS2 >= cand$start[4] & POS2 <= cand$end[4])
r2.bnc2.bnc2.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[5] & POS1 >= cand$start[5] & POS1 <= cand$end[5] & POS2 >= cand$start[5] & POS2 <= cand$end[5])
r2.bnc2.gnaq.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[5] & POS1 >= cand$start[5] & POS1 <= cand$end[5] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.bnc2.ror2.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[5] & POS1 >= cand$start[5] & POS1 <= cand$end[5] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.bnc2.apc.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[5] & POS1 >= cand$start[5] & POS1 <= cand$end[5] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.bnc2.ice1.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & CHR2 == cand$chrom[5] & POS2 >= cand$start[5] & POS2 <= cand$end[5])
r2.bnc2.pde1c.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[10] & POS1 >= cand$start[10] & POS1 <= cand$end[10] & CHR2 == cand$chrom[5] & POS2 >= cand$start[5] & POS2 <= cand$end[5])
r2.gnaq.gnaq.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[6] & POS1 >= cand$start[6] & POS1 <= cand$end[6] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.gnaq.ror2.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[6] & POS1 >= cand$start[6] & POS1 <= cand$end[6] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.gnaq.apc.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[6] & POS1 >= cand$start[6] & POS1 <= cand$end[6] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.gnaq.ice1.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & CHR2 == cand$chrom[6] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.gnaq.pde1c.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[10] & POS1 >= cand$start[10] & POS1 <= cand$end[10] & CHR2 == cand$chrom[6] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.ror2.ror2.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[7] & POS1 >= cand$start[7] & POS1 <= cand$end[7] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.ror2.apc.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[7] & POS1 >= cand$start[7] & POS1 <= cand$end[7] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.ror2.ice1.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & CHR2 == cand$chrom[7] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.ror2.pde1c.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[10] & POS1 >= cand$start[10] & POS1 <= cand$end[10] & CHR2 == cand$chrom[7] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.apc.apc.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[8] & POS1 >= cand$start[8] & POS1 <= cand$end[8] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.apc.ice1.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & CHR2 == cand$chrom[8] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.apc.pde1c.rt <- r2.sig.inter.rt %>% filter(CHR1 == cand$chrom[10] & POS1 >= cand$start[10] & POS1 <= cand$end[10] & CHR2 == cand$chrom[8] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.ice1.ice1.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & POS2 >= cand$start[9] & POS2 <= cand$end[9])
r2.ice1.pde1c.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & POS2 >= cand$start[10] & POS2 <= cand$end[10])
r2.pde1c.pde1c.rt <- r2.sig.intra.rt %>% filter(CHR == cand$chrom[10] & POS1 >= cand$start[10] & POS1 <= cand$end[10] & POS2 >= cand$start[10] & POS2 <= cand$end[10])

r2.kitlg.kitlg.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & POS2 >= cand$start[1] & POS2 <= cand$end[1])
r2.kitlg.plxnc1.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & POS2 >= cand$start[2] & POS2 <= cand$end[2])
r2.kitlg.spef2.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[3] & POS2 >= cand$start[3] & POS2 <= cand$end[3])
r2.kitlg.slc45a2.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[4] & POS2 >= cand$start[4] & POS2 <= cand$end[4])
r2.kitlg.bnc2.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[5] & POS2 >= cand$start[5] & POS2 <= cand$end[5])
r2.kitlg.gnaq.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[6] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.kitlg.ror2.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[7] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.kitlg.apc.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[8] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.kitlg.ice1.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[9] & POS2 >= cand$start[9] & POS2 <= cand$end[9])
r2.kitlg.pde1c.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[10] & POS2 >= cand$start[10] & POS2 <= cand$end[10])
r2.plxnc1.plxnc1.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & POS2 >= cand$start[2] & POS2 <= cand$end[2])
r2.plxnc1.spef2.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[3] & POS2 >= cand$start[3] & POS2 <= cand$end[3])
r2.plxnc1.slc45a2.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[4] & POS2 >= cand$start[4] & POS2 <= cand$end[4])
r2.plxnc1.bnc2.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[5] & POS2 >= cand$start[5] & POS2 <= cand$end[5])
r2.plxnc1.gnaq.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[6] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.plxnc1.ror2.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[7] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.plxnc1.apc.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[8] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.plxnc1.ice1.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[9] & POS2 >= cand$start[9] & POS2 <= cand$end[9])
r2.plxnc1.pde1c.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[10] & POS2 >= cand$start[10] & POS2 <= cand$end[10])
r2.spef2.spef2.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[3] & POS1 >= cand$start[3] & POS1 <= cand$end[3] & POS2 >= cand$start[3] & POS2 <= cand$end[3])
r2.spef2.slc45a2.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[3] & POS1 >= cand$start[3] & POS1 <= cand$end[3] & POS2 >= cand$start[4] & POS2 <= cand$end[4])
r2.spef2.bnc2.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[3] & POS1 >= cand$start[3] & POS1 <= cand$end[3] & POS2 >= cand$start[5] & POS2 <= cand$end[5])
r2.spef2.gnaq.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[3] & POS1 >= cand$start[3] & POS1 <= cand$end[3] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.spef2.ror2.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[3] & POS1 >= cand$start[3] & POS1 <= cand$end[3] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.spef2.apc.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[3] & POS1 >= cand$start[3] & POS1 <= cand$end[3] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.spef2.ice1.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & CHR2 == cand$chrom[3] & POS2 >= cand$start[3] & POS2 <= cand$end[3])
r2.spef2.pde1c.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[10] & POS1 >= cand$start[10] & POS1 <= cand$end[10] & CHR2 == cand$chrom[3] & POS2 >= cand$start[3] & POS2 <= cand$end[3])
r2.slc45a2.slc45a2.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[4] & POS1 >= cand$start[4] & POS1 <= cand$end[4] & POS2 >= cand$start[4] & POS2 <= cand$end[4])
r2.slc45a2.bnc2.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[4] & POS1 >= cand$start[4] & POS1 <= cand$end[4] & POS2 >= cand$start[5] & POS2 <= cand$end[5])
r2.slc45a2.gnaq.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[4] & POS1 >= cand$start[4] & POS1 <= cand$end[4] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.slc45a2.ror2.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[4] & POS1 >= cand$start[4] & POS1 <= cand$end[4] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.slc45a2.apc.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[4] & POS1 >= cand$start[4] & POS1 <= cand$end[4] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.slc45a2.ice1.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & CHR2 == cand$chrom[4] & POS2 >= cand$start[4] & POS2 <= cand$end[4])
r2.slc45a2.pde1c.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[10] & POS1 >= cand$start[10] & POS1 <= cand$end[10] & CHR2 == cand$chrom[4] & POS2 >= cand$start[4] & POS2 <= cand$end[4])
r2.bnc2.bnc2.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[5] & POS1 >= cand$start[5] & POS1 <= cand$end[5] & POS2 >= cand$start[5] & POS2 <= cand$end[5])
r2.bnc2.gnaq.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[5] & POS1 >= cand$start[5] & POS1 <= cand$end[5] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.bnc2.ror2.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[5] & POS1 >= cand$start[5] & POS1 <= cand$end[5] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.bnc2.apc.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[5] & POS1 >= cand$start[5] & POS1 <= cand$end[5] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.bnc2.ice1.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & CHR2 == cand$chrom[5] & POS2 >= cand$start[5] & POS2 <= cand$end[5])
r2.bnc2.pde1c.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[10] & POS1 >= cand$start[10] & POS1 <= cand$end[10] & CHR2 == cand$chrom[5] & POS2 >= cand$start[5] & POS2 <= cand$end[5])
r2.gnaq.gnaq.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[6] & POS1 >= cand$start[6] & POS1 <= cand$end[6] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.gnaq.ror2.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[6] & POS1 >= cand$start[6] & POS1 <= cand$end[6] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.gnaq.apc.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[6] & POS1 >= cand$start[6] & POS1 <= cand$end[6] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.gnaq.ice1.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & CHR2 == cand$chrom[6] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.gnaq.pde1c.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[10] & POS1 >= cand$start[10] & POS1 <= cand$end[10] & CHR2 == cand$chrom[6] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.ror2.ror2.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[7] & POS1 >= cand$start[7] & POS1 <= cand$end[7] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.ror2.apc.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[7] & POS1 >= cand$start[7] & POS1 <= cand$end[7] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.ror2.ice1.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & CHR2 == cand$chrom[7] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.ror2.pde1c.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[10] & POS1 >= cand$start[10] & POS1 <= cand$end[10] & CHR2 == cand$chrom[7] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.apc.apc.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[8] & POS1 >= cand$start[8] & POS1 <= cand$end[8] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.apc.ice1.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & CHR2 == cand$chrom[8] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.apc.pde1c.rg <- r2.sig.inter.rg %>% filter(CHR1 == cand$chrom[10] & POS1 >= cand$start[10] & POS1 <= cand$end[10] & CHR2 == cand$chrom[8] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.ice1.ice1.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & POS2 >= cand$start[9] & POS2 <= cand$end[9])
r2.ice1.pde1c.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & POS2 >= cand$start[10] & POS2 <= cand$end[10])
r2.pde1c.pde1c.rg <- r2.sig.intra.rg %>% filter(CHR == cand$chrom[10] & POS1 >= cand$start[10] & POS1 <= cand$end[10] & POS2 >= cand$start[10] & POS2 <= cand$end[10])

r2.kitlg.kitlg.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & POS2 >= cand$start[1] & POS2 <= cand$end[1])
r2.kitlg.plxnc1.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & POS2 >= cand$start[2] & POS2 <= cand$end[2])
r2.kitlg.spef2.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[3] & POS2 >= cand$start[3] & POS2 <= cand$end[3])
r2.kitlg.slc45a2.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[4] & POS2 >= cand$start[4] & POS2 <= cand$end[4])
r2.kitlg.bnc2.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[5] & POS2 >= cand$start[5] & POS2 <= cand$end[5])
r2.kitlg.gnaq.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[6] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.kitlg.ror2.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[7] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.kitlg.apc.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[8] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.kitlg.ice1.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[9] & POS2 >= cand$start[9] & POS2 <= cand$end[9])
r2.kitlg.pde1c.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[1] & POS1 >= cand$start[1] & POS1 <= cand$end[1] & CHR2 == cand$chrom[10] & POS2 >= cand$start[10] & POS2 <= cand$end[10])
r2.plxnc1.plxnc1.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & POS2 >= cand$start[2] & POS2 <= cand$end[2])
r2.plxnc1.spef2.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[3] & POS2 >= cand$start[3] & POS2 <= cand$end[3])
r2.plxnc1.slc45a2.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[4] & POS2 >= cand$start[4] & POS2 <= cand$end[4])
r2.plxnc1.bnc2.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[5] & POS2 >= cand$start[5] & POS2 <= cand$end[5])
r2.plxnc1.gnaq.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[6] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.plxnc1.ror2.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[7] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.plxnc1.apc.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[8] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.plxnc1.ice1.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[9] & POS2 >= cand$start[9] & POS2 <= cand$end[9])
r2.plxnc1.pde1c.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[2] & POS1 >= cand$start[2] & POS1 <= cand$end[2] & CHR2 == cand$chrom[10] & POS2 >= cand$start[10] & POS2 <= cand$end[10])
r2.spef2.spef2.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[3] & POS1 >= cand$start[3] & POS1 <= cand$end[3] & POS2 >= cand$start[3] & POS2 <= cand$end[3])
r2.spef2.slc45a2.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[3] & POS1 >= cand$start[3] & POS1 <= cand$end[3] & POS2 >= cand$start[4] & POS2 <= cand$end[4])
r2.spef2.bnc2.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[3] & POS1 >= cand$start[3] & POS1 <= cand$end[3] & POS2 >= cand$start[5] & POS2 <= cand$end[5])
r2.spef2.gnaq.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[3] & POS1 >= cand$start[3] & POS1 <= cand$end[3] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.spef2.ror2.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[3] & POS1 >= cand$start[3] & POS1 <= cand$end[3] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.spef2.apc.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[3] & POS1 >= cand$start[3] & POS1 <= cand$end[3] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.spef2.ice1.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & CHR2 == cand$chrom[3] & POS2 >= cand$start[3] & POS2 <= cand$end[3])
r2.spef2.pde1c.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[10] & POS1 >= cand$start[10] & POS1 <= cand$end[10] & CHR2 == cand$chrom[3] & POS2 >= cand$start[3] & POS2 <= cand$end[3])
r2.slc45a2.slc45a2.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[4] & POS1 >= cand$start[4] & POS1 <= cand$end[4] & POS2 >= cand$start[4] & POS2 <= cand$end[4])
r2.slc45a2.bnc2.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[4] & POS1 >= cand$start[4] & POS1 <= cand$end[4] & POS2 >= cand$start[5] & POS2 <= cand$end[5])
r2.slc45a2.gnaq.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[4] & POS1 >= cand$start[4] & POS1 <= cand$end[4] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.slc45a2.ror2.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[4] & POS1 >= cand$start[4] & POS1 <= cand$end[4] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.slc45a2.apc.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[4] & POS1 >= cand$start[4] & POS1 <= cand$end[4] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.slc45a2.ice1.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & CHR2 == cand$chrom[4] & POS2 >= cand$start[4] & POS2 <= cand$end[4])
r2.slc45a2.pde1c.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[10] & POS1 >= cand$start[10] & POS1 <= cand$end[10] & CHR2 == cand$chrom[4] & POS2 >= cand$start[4] & POS2 <= cand$end[4])
r2.bnc2.bnc2.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[5] & POS1 >= cand$start[5] & POS1 <= cand$end[5] & POS2 >= cand$start[5] & POS2 <= cand$end[5])
r2.bnc2.gnaq.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[5] & POS1 >= cand$start[5] & POS1 <= cand$end[5] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.bnc2.ror2.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[5] & POS1 >= cand$start[5] & POS1 <= cand$end[5] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.bnc2.apc.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[5] & POS1 >= cand$start[5] & POS1 <= cand$end[5] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.bnc2.ice1.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & CHR2 == cand$chrom[5] & POS2 >= cand$start[5] & POS2 <= cand$end[5])
r2.bnc2.pde1c.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[10] & POS1 >= cand$start[10] & POS1 <= cand$end[10] & CHR2 == cand$chrom[5] & POS2 >= cand$start[5] & POS2 <= cand$end[5])
r2.gnaq.gnaq.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[6] & POS1 >= cand$start[6] & POS1 <= cand$end[6] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.gnaq.ror2.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[6] & POS1 >= cand$start[6] & POS1 <= cand$end[6] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.gnaq.apc.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[6] & POS1 >= cand$start[6] & POS1 <= cand$end[6] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.gnaq.ice1.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & CHR2 == cand$chrom[6] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.gnaq.pde1c.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[10] & POS1 >= cand$start[10] & POS1 <= cand$end[10] & CHR2 == cand$chrom[6] & POS2 >= cand$start[6] & POS2 <= cand$end[6])
r2.ror2.ror2.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[7] & POS1 >= cand$start[7] & POS1 <= cand$end[7] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.ror2.apc.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[7] & POS1 >= cand$start[7] & POS1 <= cand$end[7] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.ror2.ice1.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & CHR2 == cand$chrom[7] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.ror2.pde1c.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[10] & POS1 >= cand$start[10] & POS1 <= cand$end[10] & CHR2 == cand$chrom[7] & POS2 >= cand$start[7] & POS2 <= cand$end[7])
r2.apc.apc.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[8] & POS1 >= cand$start[8] & POS1 <= cand$end[8] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.apc.ice1.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & CHR2 == cand$chrom[8] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.apc.pde1c.tg <- r2.sig.inter.tg %>% filter(CHR1 == cand$chrom[10] & POS1 >= cand$start[10] & POS1 <= cand$end[10] & CHR2 == cand$chrom[8] & POS2 >= cand$start[8] & POS2 <= cand$end[8])
r2.ice1.ice1.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & POS2 >= cand$start[9] & POS2 <= cand$end[9])
r2.ice1.pde1c.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[9] & POS1 >= cand$start[9] & POS1 <= cand$end[9] & POS2 >= cand$start[10] & POS2 <= cand$end[10])
r2.pde1c.pde1c.tg <- r2.sig.intra.tg %>% filter(CHR == cand$chrom[10] & POS1 >= cand$start[10] & POS1 <= cand$end[10] & POS2 >= cand$start[10] & POS2 <= cand$end[10])

### Calculate mean r2-------------------------------------------------------

r2.mean.rt <- c()
r2.mean.rt <- append(r2.mean.rt,mean(r2.kitlg.kitlg.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.kitlg.plxnc1.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.kitlg.spef2.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.kitlg.slc45a2.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.kitlg.bnc2.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.kitlg.gnaq.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.kitlg.ror2.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.kitlg.apc.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.kitlg.ice1.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.kitlg.pde1c.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.plxnc1.plxnc1.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.plxnc1.spef2.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.plxnc1.slc45a2.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.plxnc1.bnc2.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.plxnc1.gnaq.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.plxnc1.ror2.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.plxnc1.apc.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.plxnc1.ice1.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.plxnc1.pde1c.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.spef2.spef2.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.spef2.slc45a2.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.spef2.bnc2.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.spef2.gnaq.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.spef2.ror2.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.spef2.apc.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.spef2.ice1.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.spef2.pde1c.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.slc45a2.slc45a2.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.slc45a2.bnc2.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.slc45a2.gnaq.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.slc45a2.ror2.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.slc45a2.apc.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.slc45a2.ice1.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.slc45a2.pde1c.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.bnc2.bnc2.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.bnc2.gnaq.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.bnc2.ror2.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.bnc2.apc.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.bnc2.ice1.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.bnc2.pde1c.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.gnaq.gnaq.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.gnaq.ror2.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.gnaq.apc.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.gnaq.ice1.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.gnaq.pde1c.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.ror2.ror2.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.ror2.apc.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.ror2.ice1.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.ror2.pde1c.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.apc.apc.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.apc.ice1.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.apc.pde1c.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.ice1.ice1.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.ice1.pde1c.rt$R.2,na.rm=T))
r2.mean.rt <- append(r2.mean.rt,mean(r2.pde1c.pde1c.rt$R.2,na.rm=T))

r2.mean.rg <- c()
r2.mean.rg <- append(r2.mean.rg,mean(r2.kitlg.kitlg.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.kitlg.plxnc1.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.kitlg.spef2.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.kitlg.slc45a2.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.kitlg.bnc2.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.kitlg.gnaq.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.kitlg.ror2.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.kitlg.apc.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.kitlg.ice1.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.kitlg.pde1c.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.plxnc1.plxnc1.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.plxnc1.spef2.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.plxnc1.slc45a2.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.plxnc1.bnc2.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.plxnc1.gnaq.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.plxnc1.ror2.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.plxnc1.apc.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.plxnc1.ice1.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.plxnc1.pde1c.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.spef2.spef2.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.spef2.slc45a2.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.spef2.bnc2.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.spef2.gnaq.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.spef2.ror2.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.spef2.apc.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.spef2.ice1.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.spef2.pde1c.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.slc45a2.slc45a2.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.slc45a2.bnc2.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.slc45a2.gnaq.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.slc45a2.ror2.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.slc45a2.apc.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.slc45a2.ice1.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.slc45a2.pde1c.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.bnc2.bnc2.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.bnc2.gnaq.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.bnc2.ror2.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.bnc2.apc.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.bnc2.ice1.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.bnc2.pde1c.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.gnaq.gnaq.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.gnaq.ror2.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.gnaq.apc.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.gnaq.ice1.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.gnaq.pde1c.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.ror2.ror2.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.ror2.apc.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.ror2.ice1.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.ror2.pde1c.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.apc.apc.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.apc.ice1.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.apc.pde1c.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.ice1.ice1.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.ice1.pde1c.rg$R.2,na.rm=T))
r2.mean.rg <- append(r2.mean.rg,mean(r2.pde1c.pde1c.rg$R.2,na.rm=T))

r2.mean.tg <- c()
r2.mean.tg <- append(r2.mean.tg,mean(r2.kitlg.kitlg.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.kitlg.plxnc1.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.kitlg.spef2.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.kitlg.slc45a2.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.kitlg.bnc2.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.kitlg.gnaq.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.kitlg.ror2.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.kitlg.apc.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.kitlg.ice1.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.kitlg.pde1c.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.plxnc1.plxnc1.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.plxnc1.spef2.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.plxnc1.slc45a2.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.plxnc1.bnc2.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.plxnc1.gnaq.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.plxnc1.ror2.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.plxnc1.apc.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.plxnc1.ice1.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.plxnc1.pde1c.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.spef2.spef2.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.spef2.slc45a2.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.spef2.bnc2.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.spef2.gnaq.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.spef2.ror2.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.spef2.apc.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.spef2.ice1.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.spef2.pde1c.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.slc45a2.slc45a2.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.slc45a2.bnc2.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.slc45a2.gnaq.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.slc45a2.ror2.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.slc45a2.apc.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.slc45a2.ice1.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.slc45a2.pde1c.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.bnc2.bnc2.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.bnc2.gnaq.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.bnc2.ror2.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.bnc2.apc.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.bnc2.ice1.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.bnc2.pde1c.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.gnaq.gnaq.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.gnaq.ror2.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.gnaq.apc.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.gnaq.ice1.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.gnaq.pde1c.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.ror2.ror2.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.ror2.apc.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.ror2.ice1.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.ror2.pde1c.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.apc.apc.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.apc.ice1.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.apc.pde1c.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.ice1.ice1.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.ice1.pde1c.tg$R.2,na.rm=T))
r2.mean.tg <- append(r2.mean.tg,mean(r2.pde1c.pde1c.tg$R.2,na.rm=T))

for (i in r2.mean.rt){
  print(i)
}

for (i in r2.mean.rg){
  print(i)
}

for (i in r2.mean.tg){
  print(i)
}

